Can't follow a certain identi.ca accounts
https://github.com/e14n/pump.io/issues/982

some profiles have the value  "upstreamDuplicates" set.if this is set to:
"upstreamDuplicates":{"0":"http://identi.ca/user/12345"} the function throws:
```
Error: Remote OAuth error code 500: TypeError: upstreamDuplicates is not an array
```